apiVersion: v1
kind: Service
metadata:
  name: weatherprediction
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: weatherprediction