apiVersion: v1
kind: Service
metadata:
  name: weatherprediction
spec:
  type: NodePort
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30005
      protocol: TCP
  selector:
    app: weatherprediction